CREATE DATABASE IF NOT EXISTS LibraryDatabase;
USE LibraryDatabase;

CREATE TABLE IF NOT EXISTS Author(
	AuthorId INT PRIMARY KEY NOT NULL,
    FirstName VARCHAR(25) NOT NULL,
    MiddleName VARCHAR(25),
    LastName VARCHAR(50) NOT NULL,
    Gender VARCHAR(1),
    DateOfBirth DATETIME NOT NULL,
    DateOfDeath DATETIME
);

CREATE TABLE IF NOT EXISTS Genre(
	GenreId INT PRIMARY KEY NOT NULL,
    GenreName VARCHAR(25) NOT NULL
);

CREATE TABLE IF NOT EXISTS Book(
	BookId INT PRIMARY KEY NOT NULL,
    AuthorId INT NOT NULL,
    GenreId INT NOT NULL,
    Title VARCHAR(100) NOT NULL,
    Synopsis VARCHAR(500),
    PublicationDate DATETIME,
    FOREIGN KEY (AuthorId) REFERENCES Author(AuthorId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (GenreId) REFERENCES Genre(GenreId) ON DELETE CASCADE ON UPDATE CASCADE
);